### ISSUE TITLE
[Bug] Shr-next-link and shrface-*-consult command does not work as expected

### ISSUE THREAD

**Issue by idlip** [chenyanming/shrface#19]
First of all, Nice package. I love reading in emacs alot, even doing browser stuff now that eww is like org-mode lol.

1. `shrface-*-consult` shows the candidates properly, but when I enter, it does not move to that place.
Gives out error like:

``` emacs-lisp
Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>, 4 [2 times]
```

Consult used built-in emacs functionality, enhancing completing-read.
So it should not be much of a hassle to make it work.

2. We use `<tab>` for toggle heading. So I'd would like to bind `M-n` to `shr-next-link`, but it does not work as expected.
It simply says: `No Next link`

Lemme know if there is another way to jumping to links back and forth.

**Comment by gopar** [comment]
Same issue about consult commands. Thanks for the work!

**Comment by idlip** [comment]
@gopar Thank you for the fix, it works now.
But the preview does not work?
Like how consult-line shows preview of the line, this does not show where the link is.

@chenyanming Still `shr-next/prev-link` does not work.

**Comment by gopar** [comment]
> @gopar Thank you for the fix, it works now. But the preview does not work? Like how consult-line shows preview of the line, this does not show where the link is.

I don't know much about consult. Just knew enough to fix. That is working

> @chenyanming Still `shr-next/prev-link` does not work.

Open another issue. This is unrelated. Also, I don't think those function do what you think they do, some sites have links that are labeled as "next" and "prev". I believe those are supposed to be following in those functions

**Comment by idlip** [comment]
> I don't know much about consult. Just knew enough to fix. That is working
No worries.

> Open another issue. This is unrelated. Also, I don't think those function do what you think they do, some sites have links that are labeled as "next" and "prev". I believe those are supposed to be following in those functions

I think you got confused, what you are referring to is `eww-next-url` & `eww-prev-url`.
I was talking about `shr-next-link` which is default behavior TAB for cycling links in the webpage page.

**Comment by gopar** [comment]
> > Open another issue. This is unrelated. Also, I don't think those function do what you think they do, some sites have links that are labeled as "next" and "prev". I believe those are supposed to be following in those functions
> 
> I think you got confused, what you are referring to is `eww-next-url` & `eww-prev-url`. I was talking about `shr-next-link` which is default behavior TAB for cycling links (next urls) in the webpage page.

Ah, you are right! But still a good idea to open another issue. The consult functions and next/prev functions are unrelated. They should not be bundled together. :)

Makes bug tracking easier for everyone \o/
