### ISSUE TITLE
support org-superstar alternatively to replace org-bullets

### ISSUE THREAD

**Issue by stardiviner** [chenyanming/shrface#2]
As the title said.

I found `org-superstar` have better features. And `org-bullets` is not maintained for a long time.
So I think `org-superstar` support is useful.

**Comment by chenyanming** [comment]
> As the title said.
> 
> I found `org-superstar` have better features. And `org-bullets` is not maintained for a long time.
> So I think `org-superstar` support is useful.

**Comment by chenyanming** [comment]
org-superstar looks nice. I will add it in the future.

**Comment by chenyanming** [comment]
@stardiviner `org-superstar-headline-bullets-list` is supported now.

**Comment by stardiviner** [comment]
That's great! I confirmed this new update. Thanks!!!
