### ISSUE TITLE
Problem installing it with straight

### ISSUE THREAD

**Issue by ram535** [chenyanming/shrface#4]
I get this message when I start emacs after trying to install `shrface`.

```
Error (use-package): shrface/:catch: Cannot open load file: No such file or directory, org-bullets
```

This my config:
```
(use-package shrface
 :after shr
 :straight (shrface :type git :host github :repo "chenyanming/shrface")) 
```

**Comment by ram535** [comment]
Never mind, I just need to install org-bullets. I should pay more attention to the readme next time.

**Comment by chenyanming** [comment]
Thanks for your reminding. I also updated the readme.

**Comment by chenyanming** [comment]
> Never mind, I just need to install org-bullets. I should pay more attention to the readme next time.

Thanks for reminding me. I also updated the readme.
